### ISSUE TITLE
XMLServer pod failing to start with chmod permission error

### ISSUE THREAD

**Issue by podgek** [merative/spm-kubernetes#108]
Currently installing SPM on OpenShift on Azure ARO. The install is successful (all but one pods start up successfully and we can log into the Curam app) except for when the xmlserver pod is trying to launch. As part of launching, it is running the xmlserver.xml ant file. There is a line in there that is attempting to chmod the xmlserverprint.sh file. This fails. See log below (obtained from "oc logs pod/podname"). We're a bit stumped as to the cause of this. 

[wasadm@openshift helm-charts]$ oc logs pod/release1-xmlserver-8d5c9ff7-l779k
tee: tmp/xmlserver.log: No such file or directory
Buildfile: /opt/ibm/Curam/xmlserver/xmlserver.xml

checkkeystore:

createkeystore:

check.certificate:

exportcert:
[exec] Certificate stored in file <./tls.crt>
[echo] Certificate exported from keystore

listcerts:

deletecert:

importcert:
[echo] Certificate (./tls.crt) has been imported into client's CA truststore (/opt/ibm/java/jre/lib/security/cacerts).

main:
[mkdir] Created dir: /opt/ibm/Curam/xmlserver/tmp
[mkdir] Created dir: /opt/ibm/Curam/xmlserver/template
[mkdir] Created dir: /opt/ibm/Curam/xmlserver/stats
[copy] Copying 1 file to /opt/ibm/Curam/xmlserver
[chmod] chmod: changing permissions of '/opt/ibm/Curam/xmlserver/xmlserverprint.sh': Operation not permitted
[chmod] Result: 1
[xmlserver] [INFO] [XMLServer] -------------------------------------------------------------------------------
[xmlserver] [INFO] [XMLServer] Curam XML Server
[xmlserver] Copyright (c) 2012 IBM Corporation.
[xmlserver]
[xmlserver] [INFO] [XMLServer] Started : Wed Feb 02 22:30:37 UTC 2022
[xmlserver] [INFO] [XMLServer] -------------------------------------------------------------------------------
[xmlserver] [ERROR] [XMLServer]
[xmlserver] ERROR: incorrect usage.
[xmlserver]
[xmlserver] [INFO] [XMLServer] Usage:
[xmlserver] [INFO] [XMLServer] XMLServer -c <config-file> [-novalidation]

BUILD SUCCESSFUL
Total time: 17 seconds

**Comment by ourboy** [comment]
@podgek 

Can you confirm the following:

What version of OpenShift are you using?
What version of SPM are you using?
What version of SPM-Kubernetes runbook are you using?

**Comment by praveenporeddy89** [comment]
Hi @ourboy 

Below are details:

What version of OpenShift are you using? azure aro version is  4.8.18
What version of SPM are you using? 8.0.0.0
What version of SPM-Kubernetes runbook are you using? "21.12.0"

**Comment by ourboy** [comment]
@praveenporeddy89 

Thank you for the information.

the `21.12.0` release contains breaking changes for deployment of SPM 8.0.0.0, and as such can only be ran against SPM8.0.1.0 or greater. This note was missing from the release, and has now been added, see update note[ [SPM v8] December Release 2021](https://github.com/IBM/spm-kubernetes/releases/tag/21.12.0)

if you roll back to version `21.10.0` recreated your containers and redeploy, you should no longer encounter the xmlserver issue.

**Comment by praveenporeddy89** [comment]
@ourboy 

Thanks for info. How can we downgrade from 21.12.0 to 21.10.0? Should that be like new installation or any inplace downgrade?

**Comment by podgek** [comment]
@praveenporeddy89 go here: https://github.com/IBM/spm-kubernetes/releases/tag/21.10.0

Scroll down and expand the Assets section. Download the "Source Code (zip)".

Safest bet is to rebuild your docker images, repush and helm install again.

**Comment by ourboy** [comment]
@praveenporeddy89 

there are 2 way. 
1. you can download the source directly here [ [SPM v8] October Release 2021](https://github.com/IBM/spm-kubernetes/releases/tag/21.10.0)
2. Alternatively you can run the following command on your local copy `git checkout tags/21.10.0` and this will set your local copy to `21.10.0`

**Comment by praveenporeddy89** [comment]
Hi @ourboy 

1) Currently there are few config files that we modified in spm_kubernetes parent directory that is in 21.12.0
2) If we downgrade, do you have list of what files are changed between this two versions?

**Comment by podgek** [comment]
@praveenporeddy89 what files are you thinking of? I think all changes were done in the override YAML file, or should have been. Nothing should have been changed in the spm_kubernetes parent directory. But let us know what files you are thinking of?

**Comment by wwwild** [comment]
Is this issue still relevant? 

It has been quite some time since the last update. If there is no further update we will close this issue.

**Comment by Bosco2k6** [comment]
No longer relevant/clise it up. Ty!
