### ISSUE TITLE
Unnecessary text presented on each page of the Runbook

### ISSUE THREAD

**Issue by khippsley** [merative/spm-kubernetes#130]
At the top of each page of the runbook there is "title", "description" and sometimes "tabs" information displayed unnecessarily (e.g. "title: SPM on Kubernetes 101 description: SPM on Kubernetes 101 tabs: [‘SPM on Kubernetes 101’,‘What is Containerization?’, ‘What is Helm?’, ‘What is Kubernetes?’,‘What is OpenShift?’]") - see screenshot:

<img width="1107" alt="Screen Shot 2022-08-15 at 5 06 22 PM" src="https://user-images.githubusercontent.com/14776293/184756646-af0a1179-6402-4873-b14a-4a04eca548ee.png">

**Comment by khippsley** [comment]
FYI: The url was: https://merative.github.io/spm-kubernetes/architecture/kubernetes/spm-on-kubernetes-101/

**Comment by wwwild** [comment]
With the [November 2022 Runbook release](https://github.com/merative/spm-kubernetes/releases/tag/22.11.0) this has been corrected; for example: https://merative.github.io/spm-kubernetes/architecture/kubernetes/spm-on-kubernetes-101/
