### ISSUE TITLE
Documentation Discrepancies on SPM's Architecture Support for IBM MQ Container on OpenShift 

### ISSUE THREAD

**Issue by surkramu** [merative/spm-kubernetes#132]
ESDC Client raised a query whether the Product supports deploying MQ as a Container on OpenShift based on some statements found in Knowledge Center/Documentations. Please refer some of the references below:

https://www.ibm.com/docs/en/spm/8.0.2?topic=architecture-messaging

![image](https://user-images.githubusercontent.com/58842401/195864855-e48806bc-217b-4046-ab6b-50c5b08955d7.png)

https://merative.github.io/spm-kubernetes/architecture/arch-overview/spm-openshift-reference-architecture

![image](https://user-images.githubusercontent.com/58842401/195864951-02ddd736-4cd0-41ee-bdac-c52ea04d78d0.png)

It was later clarified that this is a documentation error and will be corrected. This ticket is raised to track that correction.

Please note: In other places like below, we see the Product indeed supports such deployment architecture.

https://merative.github.io/spm-kubernetes/architecture/arch-overview/architecture-overview/
https://merative.github.io/spm-kubernetes/architecture/arch-overview/spm-openshift-reference-architecture

**Comment by wwwild** [comment]
With the [November 2022 Runbook release](https://github.com/merative/spm-kubernetes/releases/tag/22.11.0) the text has been updated to address this; see: https://merative.github.io/spm-kubernetes/architecture/arch-overview/spm-openshift-reference-architecture
