### ISSUE TITLE
Database connection authorization Failure in Producer log

### ISSUE THREAD

**Issue by podgek** [merative/spm-kubernetes#92]
We can get to the Curam login screen, but when we attempt to login, we just get a white screen. Looking in the logs of a producer pod we see the error: `[ERROR   ] Exception is: [jcc][t4][2013][11249][4.28.11] Connection authorization failure occurred.  Reason: User ID or Password invalid. ERRORCODE=-4214, SQLSTATE=28000 DSRA0010E: SQL State = 28000, Error Code = -4,214`. 

We believe that we have setup the relevant database properties correctly in our values.yaml file, and have encrypted the password correctly. We are struggling to debug this further and get to the root of the problem. We are not sure what the Helm install scripts are doing with these properties. If we knew that we could dig around further. The log file from the producer pod is attached here
[producer.log](https://github.com/IBM/spm-kubernetes/files/7297506/producer.log)
.

**Comment by podgek** [comment]
@Bosco2k6 see here: https://www.ibm.com/docs/en/was-liberty/base?topic=center-logging-in-admin
Not sure if you need to be in the pod container for this though? Does each pod have it's own instance of liberty running?

**Comment by ourboy** [comment]
Closing.  updated as part of V8.0.1 December release
