### ISSUE TITLE
Documentation on the values.yaml Settings

### ISSUE THREAD

**Issue by podgek** [merative/spm-kubernetes#93]
Kev and I have completed the deployment we have been working on. We struggled a bit with the values.yaml settings that were needed. We got through it by comparing with various values.yaml files from working deployments, but it felt a bit hap-hazard. We know that the configuration settings are documented in the runbook, but it was difficult, in some cases, to put 2 and 2 together to figure out what the documentation was telling us. One suggestion here is to add some comments in the provided YAML files. Also, we feel that a worked through example would be very helpful... perhaps a values.yaml file with a bunch of commented overrides in place, based on an example project name and registry, assuming a deployment of curam, CE, birt and rest. etc. Also  we're still a bit confused by some of the main blocks in the values.yaml file, for example the later blocks that are "turned-off" by default using "{}" - still not sure what they are there for (a comment highlighting the need to remove these braces if using any of the subsequent overrides would have been useful - yes I know we should be able to figure that out, and we did, but anything to reduce the cognitive load around this stuff would be appreciated).

In general through the documentation was great, and we are not suggesting here the need for a fundamental change, rather the provision of some worked through examples.

**Comment by wwwild** [comment]
Closing as enhancement has been logged internally for follow-up.
